void Show4Analog() {
  oled.clear();
  oled.textSize(1);
  oled.text(0,1,"Black");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  StartTimer();
  beep(1);
  sw_ok_unpress();
  Read2Analog();
  RefL1 = L1;
  RefR1 = R1;
  oled.text(2,0,"L1=%d",L1);
  oled.text(3,0,"R1=%d",R1);
  oled.text(0,7,"White");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  Read2Analog();
  oled.text(2,8,"L1=%d",L1);
  oled.text(3,8,"R1=%d",R1);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep();
  oled.text(0,14,"Average");
  RefL1 = (RefL1+L1)/2;
  RefR1 = (RefR1+R1)/2;
  oled.text(2,17,"%d",RefL1);
  oled.text(3,17,"%d",RefR1);
  oled.text(4,1,"Black");
  oled.show();
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  Read2AnalogBack();
  RefBL1 = BL1;
  RefBR1 = BR1;
  oled.text(5,0,"BL1=%d",BL1);
  oled.text(6,0,"BR1=%d",BR1);
  oled.text(4,7,"White");
  oled.show(); 
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  Read2AnalogBack();
  oled.text(5,8,"BL1=%d",BL1);
  oled.text(6,8,"BR1=%d",BR1);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(3);
  oled.text(0,14,"Average");
  RefBL1 = (RefBL1+BL1)/2;
  RefBR1 = (RefBR1+BR1)/2;
  oled.text(5,17,"%d",RefBL1);
  oled.text(6,17,"%d",RefBR1);
  oled.show();
  sw_ok_unpress();
}
