void Show4Analog() {
  oled.clear();
  oled.textSize(1);
  oled.text(0,1,"Black");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  StartTimer();
  beep(1);
  sw_ok_unpress();
  Read4Analog();
  RefL2 = L2;
  RefL1 = L1;
  RefR1 = R1;
  RefR2 = R2;
  oled.text(1,0,"L2=%d",L2);
  oled.text(2,0,"L1=%d",L1);
  oled.text(3,0,"R1=%d",R1);
  oled.text(4,0,"R2=%d",R2);
  oled.text(0,7,"White       ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  Read4Analog();
  oled.text(1,8,"L2=%d",L2);
  oled.text(2,8,"L1=%d",L1);
  oled.text(3,8,"R1=%d",R1);
  oled.text(4,8,"R2=%d",R2);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(3);
  oled.text(0,14,"Average");
  RefL2 = (RefL2+L2)/2;
  RefL1 = (RefL1+L1)/2;
  RefR1 = (RefR1+R1)/2;
  RefR2 = (RefR2+R2)/2;
  oled.text(1,17,"%d",RefL2);
  oled.text(2,17,"%d",RefL1);
  oled.text(3,17,"%d",RefR1);
  oled.text(4,17,"%d",RefR2);
  oled.show();
  sw_ok_unpress();
}
